---
title: "p8105_hw1_jsm2298"
author: "Jonathan Morris"
date: "2026-09-22"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages
```{r}
library(tidyverse)
library(ggplot2)
library(palmerpenguins)
```


# Question 1: 

## Load Data
```{r}
data("penguins", package = "palmerpenguins")
```
## Penguins Data Description:


## Penguin Data Scatterplot:
```{r, echo = F, warnings = F}
p <- ggplot(penguins, aes(x = flipper_length_mm, y = bill_length_mm, color = species)) + 
  geom_point() + 
  labs(x = 'Flipper Length (mm)', y = 'Bill Length (mm)', color = 'Species') +
  ggtitle("Scatterplot of Penguin Flipper vs Bill Length Across Species")

print(p)

ggsave('p8105_hw1_plot01.png', p)
```

# Question 2:

## Create Data Frame:
```{r}
## First, set our seed for reproducibility:
set.seed(112)

## Now generate the data:
rand_df <- tibble(
  rand_num = rnorm(10),
  rand_logic = case_when(
    rand_num > 0 ~ TRUE,
    TRUE ~ FALSE
  ),
  rand_char = c('my', 'all', 'time', 'favorite', 'alliums', 'are', "the", "onion", "and", "scallion"),
  rand_fac = as.factor(rbinom(10, 2, 0.5))
)
```

## Attempt to take some means:

